version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ubuntu/ec2-user-django-at-lyskills
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: /app/scripts/deploy.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /app/scripts/after.sh
      timeout: 300
      runas: root