version: '3.6'

services:
  db:
    container_name:  db_django
    image: postgres:15.4
    ports:
      - '5433:5432'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/postgresql"
      - /tmp/app/postgresql:/var/run/postgresql

    environment:
       POSTGRES_DB: 'django_blog_posts_bk'
       POSTGRES_USER: 'postgres'
       POSTGRES_PASSWORD: 'root'
       PGUSER: 'postgres'

  web:
    container_name:  app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /tmp/app/postgresql:/run/postgresql
    restart: unless-stopped
    # network_mode: 127.0.0.1
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data: